/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.registration.model.impl;

import com.liferay.training.registration.model.User_;
import com.liferay.training.registration.service.User_LocalServiceUtil;

/**
 * The extended model base implementation for the User_ service. Represents a row in the &quot;Registration_User_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link User_Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see User_Impl
 * @see User_
 * @generated
 */
public abstract class User_BaseImpl extends User_ModelImpl implements User_ {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user_ model instance should use the <code>User_</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			User_LocalServiceUtil.addUser_(this);
		}
		else {
			User_LocalServiceUtil.updateUser_(this);
		}
	}

}